name:                sealed-server
version:             0.1.0.0
github:              "githubuser/sealed-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sealed-server#readme>

dependencies:
- base >= 4.7 && < 5
- scotty >= 0.11.2 && < 0.12
- aeson >= 1.3.1.1 && < 1.4
- uuid >= 1.3.13 && < 1.4
- text >= 1.2.3 && < 1.3

library:
  source-dirs: src

executables:
  sealed-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sealed-server

tests:
  sealed-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sealed-server
